'use client';

import Header from '@/components/layout/header';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Bot, Lightbulb, Check, Zap, Recycle } from 'lucide-react';

const recommendations = [
  {
    title: 'Optimize HVAC System Schedule',
    category: 'Energy Savings',
    impact: 'High',
    description: 'Our analysis shows your HVAC system runs at full capacity during non-operational hours (10 PM - 6 AM). Adjusting the schedule could reduce energy consumption by up to 18%.',
    icon: <Zap className="h-5 w-5 text-yellow-400" />,
  },
  {
    title: 'Upgrade to LED Lighting in Warehouse B',
    category: 'Energy Savings',
    impact: 'Medium',
    description: 'Warehouse B is still using fluorescent lighting. Upgrading to LED equivalents can decrease lighting-related energy costs by 60% and reduce maintenance cycles.',
    icon: <Lightbulb className="h-5 w-5 text-yellow-400" />,
  },
  {
    title: 'Implement Water Recycling for Cooling Towers',
    category: 'Water Conservation',
    impact: 'High',
    description: 'Your Peenya facility\'s cooling towers use a single-pass water system. Implementing a recycling system could save an estimated 500,000 liters of water per month.',
    icon: <Recycle className="h-5 w-5 text-blue-400" />,
  },
];

const impactStyles = {
    High: "bg-red-500/20 text-red-400 border-red-500/30",
    Medium: "bg-yellow-500/20 text-yellow-400 border-yellow-500/30",
    Low: "bg-green-500/20 text-green-400 border-green-500/30"
};

export default function RecommendationsPage() {
  return (
    <div className="flex min-h-screen flex-col bg-background text-foreground">
      <Header />
      <main className="flex-grow container py-12">
        <div className="text-center mb-12">
          <Bot className="h-12 w-12 text-primary mx-auto mb-4" />
          <h1 className="text-4xl font-bold tracking-tight">
            AI-Powered Recommendations
          </h1>
          <p className="text-muted-foreground mt-2 max-w-2xl mx-auto">
            Actionable insights generated by PRISM to improve efficiency and reduce your environmental footprint.
          </p>
        </div>

        <div className="space-y-6 max-w-4xl mx-auto">
          {recommendations.map((rec, index) => (
            <Card key={index} className="bg-card/40 border-border/30">
              <CardHeader>
                <div className="flex items-start justify-between gap-4">
                    <div className="flex items-center gap-3">
                        {rec.icon}
                        <CardTitle className="text-xl">{rec.title}</CardTitle>
                    </div>
                    <Badge variant="outline" className={impactStyles[rec.impact as keyof typeof impactStyles]}>
                        {rec.impact} Impact
                    </Badge>
                </div>
                <CardDescription>{rec.category}</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <p className="text-muted-foreground">{rec.description}</p>
                <div className="flex gap-2">
                    <Button>
                        <Check className="mr-2 h-4 w-4" /> Mark as Implemented
                    </Button>
                    <Button variant="ghost">Dismiss</Button>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      </main>
    </div>
  );
}
